import { describe, expect, it } from "vitest";
import urdf from "../../public/models/mg400/mg400_description/urdf/mg400_description.urdf?raw";
import { DEFAULT_PROJECT } from "../data/defaultProject";
import { FORK_SUPPORT_HEIGHT_MM, JOINT_LIMITS_DEG, rad, type JointAngles, type Pose } from "../domain";
import { MG400Kinematics } from "./mg400Kinematics";
import { forkEntryPose } from "./forkTool";

const kinematics = MG400Kinematics.fromUrdf(urdf);
const flange = DEFAULT_PROJECT.tool.flangeOffset;
const tcp = DEFAULT_PROJECT.tool.tcpOffsets[DEFAULT_PROJECT.tool.mode];
const fkGoldenVectors: Array<{ name: string; degrees: [number, number, number, number]; pose: Pose }> = [
  { name: "nonzero", degrees: [18, 44, 58, -18], pose: { x: 364.8425562, y: 100.67429842, z: 148.95245243, r: 0 } },
  { name: "J1_min", degrees: [-160, 30, 45, 0], pose: { x: -364.06810055, y: -130.69010068, z: 199.65466537, r: -160 } },
  { name: "J1_max", degrees: [160, 30, 45, 0], pose: { x: -364.06810055, y: 130.69010068, z: 199.65466537, r: 160 } },
  { name: "J2_min", degrees: [0, -25, 45, 0], pose: { x: 215.61067422, y: 0, z: 205.73422042, r: 0 } },
  { name: "J2_max", degrees: [0, 85, 45, 0], pose: { x: 464.76573352, y: 0, z: 63.87319598, r: 0 } },
  { name: "J3_min", degrees: [0, 30, -25, 0], pose: { x: 408.29272786, y: 0, z: 397.97018823, r: 0 } },
  { name: "J3_max", degrees: [0, 30, 105, 0], pose: { x: 208.94610442, y: 0, z: 151.2280864, r: 0 } },
  { name: "J4_min", degrees: [0, 30, 45, -360], pose: { x: 377.11229141, y: 0, z: 199.65466537, r: 0 } },
  { name: "J4_max", degrees: [0, 30, 45, 360], pose: { x: 377.11229141, y: 0, z: 199.65466537, r: 0 } },
];

function readUrdfMotionLimitDegrees(jointName: string): [number, number] {
  const joint = urdf.match(new RegExp('<joint\\b(?=[^>]*\\bname="' + jointName + '")[^>]*>([\\s\\S]*?)<\\/joint>', "i"))?.[1];
  const limit = joint?.match(/<limit\b[^>]*\blower="([^"]+)"[^>]*\bupper="([^"]+)"/i);
  if (!limit) throw new Error(`Pinned URDF motion joint ${jointName} is missing a lower/upper limit.`);
  const toDegrees = (radians: string) => Math.round((Number(radians) * 180 / Math.PI) * 100) / 100;
  return [toDegrees(limit[1]), toDegrees(limit[2])];
}

describe("MG400 model kinematics", () => {
  it("matches an independently evaluated zero-joint reference vector", () => {
    // Source URDF main-chain origins, converted from metres to millimetres:
    // x = -5 + 43.5007595 - 1.0512570 + 174.9697841 + 65.9996239
    // z = 109 + 118.9956826 + 175.0011643 + 3.2518714 + 31.0008007 - 85 - 5
    const pose = kinematics.forward([0, 0, 0, 0], flange, tcp);
    expect(pose.x).toBeCloseTo(338.41891, 2);
    expect(pose.y).toBeCloseTo(0, 2);
    expect(pose.z).toBeCloseTo(347.24952, 2);
    expect(pose.r).toBeCloseTo(0, 3);
  });

  it("matches independent Python-matrix FK vectors at a nonzero pose and every joint boundary", () => {
    // Golden vectors are regenerated by the standard-library evaluator at
    // .scratch/mg400-virtual-training-simulator/evidence/independent_mg400_fk_reference.py.
    // It independently parses the pinned URDF and does not call the product's FK code.
    for (const vector of fkGoldenVectors) {
      const joints = vector.degrees.map(rad) as JointAngles;
      const actual = kinematics.forward(joints, flange, tcp);
      expect(actual.x, vector.name).toBeCloseTo(vector.pose.x, 2);
      expect(actual.y, vector.name).toBeCloseTo(vector.pose.y, 2);
      expect(actual.z, vector.name).toBeCloseTo(vector.pose.z, 2);
      expect(actual.r, vector.name).toBeCloseTo(vector.pose.r, 2);
    }
  });

  it("uses the versioned guide's inclusive joint bounds and keeps boundary IK solutions within them", () => {
    expect(JOINT_LIMITS_DEG).toEqual([
      { min: -160, max: 160 },
      { min: -25, max: 85 },
      { min: -25, max: 105 },
      { min: -360, max: 360 },
    ]);

    for (const vector of fkGoldenVectors.filter(({ name }) => /^J[1-4]_(min|max)$/.test(name))) {
      const joints = vector.degrees.map(rad) as JointAngles;
      const solved = kinematics.solve(vector.pose, joints, flange, tcp);
      expect(solved.ok, `${vector.name} should be accepted at the inclusive guide boundary`).toBe(true);
      solved.joints.forEach((angle, index) => {
        const limits = JOINT_LIMITS_DEG[index];
        expect(angle, `${vector.name} J${index + 1} lower`).toBeGreaterThanOrEqual(rad(limits.min));
        expect(angle, `${vector.name} J${index + 1} upper`).toBeLessThanOrEqual(rad(limits.max));
      });
      expect(solved.joints[Number(vector.name[1]) - 1] * 180 / Math.PI).toBeCloseTo(vector.degrees[Number(vector.name[1]) - 1], 2);
    }
  });

  it("keeps the pinned URDF motion-joint limits distinct from Dobot product limits", () => {
    expect(["j1", "j2", "j3", "j4"].map(readUrdfMotionLimitDegrees)).toEqual([
      [-179.91, 179.91],
      [-8.02, 79.64],
      [0, 79.64],
      [-179.91, 179.91],
    ]);
  });

  it("solves every taught reference-cell waypoint within the official joint limits", () => {
    const home = DEFAULT_PROJECT.points.find((point) => point.name === "Home");
    if (!home || home.kind !== "joint") throw new Error("Fixture is missing Home.");
    let seed: JointAngles = [...home.joints];
    for (const point of DEFAULT_PROJECT.points) {
      if (point.kind !== "cartesian") continue;
      const result = kinematics.solve(point.pose, seed, flange, tcp);
      expect(result.ok, `${point.name} should be reachable; residual ${result.positionErrorMm.toFixed(2)} mm / ${result.angleErrorDeg.toFixed(2)}°`).toBe(true);
      if (result.ok) seed = result.joints;
    }
  });

  it("reaches and linearly traverses the default passive-fork pick-and-place path", () => {
    const home = DEFAULT_PROJECT.points.find((point) => point.name === "Home");
    if (!home || home.kind !== "joint") throw new Error("Fixture is missing Home.");
    const project = structuredClone(DEFAULT_PROJECT);
    project.tool.mode = "fork";
    const fork = project.tool.tcpOffsets.fork;
    const pick: Pose = { x: 360, y: -80, z: FORK_SUPPORT_HEIGHT_MM, r: 0 };
    const entry = forkEntryPose(pick);
    const lifted: Pose = { ...pick, z: FORK_SUPPORT_HEIGHT_MM + 80 };
    const place: Pose = { x: 360, y: 80, z: FORK_SUPPORT_HEIGHT_MM, r: 0 };
    const placeAbove: Pose = { ...place, z: FORK_SUPPORT_HEIGHT_MM + 80 };
    let seed: JointAngles = [...home.joints];

    const solve = (pose: Pose, label: string) => {
      const result = kinematics.solve(pose, seed, project.tool.flangeOffset, fork);
      expect(result.ok, `${label} should be reachable; residual ${result.positionErrorMm.toFixed(2)} mm / ${result.angleErrorDeg.toFixed(2)}°`).toBe(true);
      if (result.ok) seed = result.joints;
    };
    const line = (from: Pose, to: Pose, label: string) => {
      for (let step = 1; step <= 8; step += 1) {
        const t = step / 8;
        solve({
          x: from.x + (to.x - from.x) * t,
          y: from.y + (to.y - from.y) * t,
          z: from.z + (to.z - from.z) * t,
          r: from.r + (to.r - from.r) * t,
        }, `${label} (${step}/8)`);
      }
    };

    solve(entry, "fork entry");
    line(entry, pick, "fork insertion");
    line(pick, lifted, "fork lift");
    solve(placeAbove, "drop approach");
    line(placeAbove, place, "fork lower and release");
    line(place, placeAbove, "fork retract");
  }, 30_000);

  it("rejects unreachable targets and reproduces a valid forward pose", () => {
    const source: JointAngles = [rad(18), rad(44), rad(58), rad(-18)];
    const expected = kinematics.forward(source, flange, tcp);
    const solved = kinematics.solve(expected, [rad(0), rad(30), rad(45), rad(0)], flange, tcp);
    expect(solved.ok).toBe(true);
    if (solved.ok) {
      const actual = kinematics.forward(solved.joints, flange, tcp);
      expect(Math.hypot(actual.x - expected.x, actual.y - expected.y, actual.z - expected.z)).toBeLessThan(0.5);
      expect(Math.abs(actual.r - expected.r)).toBeLessThan(0.1);
    }
    const unreachable = kinematics.solve({ x: 1200, y: 0, z: 500, r: 0 }, [0, 0, 0, 0], flange, tcp);
    expect(unreachable.ok).toBe(false);
    unreachable.joints.forEach((angle, index) => {
      expect(angle).toBeGreaterThanOrEqual(rad(JOINT_LIMITS_DEG[index].min));
      expect(angle).toBeLessThanOrEqual(rad(JOINT_LIMITS_DEG[index].max));
    });
  });
});
