// Executed inside local Pyodide only. It parses the suggestion into an AST and
// reads names/call sites without importing or executing the student's program.
export const PYTHON_ANALYSIS = [
  "import ast as __ast, json as __json, re as __re",
  "__tree = __ast.parse(__ai_source, filename='<ai-suggestion>')",
  "__defined = set()",
  "__calls = []",
  "for __node in __ast.walk(__tree):",
  "    if isinstance(__node, __ast.Name) and isinstance(__node.ctx, __ast.Store):",
  "        __defined.add(__node.id)",
  "    elif isinstance(__node, (__ast.FunctionDef, __ast.AsyncFunctionDef, __ast.ClassDef)):",
  "        __defined.add(__node.name)",
  "        if isinstance(__node, (__ast.FunctionDef, __ast.AsyncFunctionDef)):",
  "            __args = __node.args.posonlyargs + __node.args.args + __node.args.kwonlyargs",
  "            __defined.update(__arg.arg for __arg in __args)",
  "            if __node.args.vararg is not None: __defined.add(__node.args.vararg.arg)",
  "            if __node.args.kwarg is not None: __defined.add(__node.args.kwarg.arg)",
  "    elif isinstance(__node, __ast.Lambda):",
  "        __args = __node.args.posonlyargs + __node.args.args + __node.args.kwonlyargs",
  "        __defined.update(__arg.arg for __arg in __args)",
  "    elif isinstance(__node, (__ast.Import, __ast.ImportFrom)):",
  "        __defined.update(__alias.asname or __alias.name.split('.')[0] for __alias in __node.names)",
  "for __node in __ast.walk(__tree):",
  "    if not isinstance(__node, __ast.Call): continue",
  "    __member = isinstance(__node.func, __ast.Attribute)",
  "    if isinstance(__node.func, __ast.Name): __name = __node.func.id",
  "    elif __member: __name = __node.func.attr",
  "    else: continue",
  "    if __re.match(r'(?i)^(mov|move|joint|rel|do|pick|place|speed|acc|get|arc|circle|jump|servo|set_do|set_tool|set_user)', __name) is None: continue",
  "    __target = __node.args[0].id if __node.args and isinstance(__node.args[0], __ast.Name) else None",
  "    __calls.append({'name': __name, 'line': __node.lineno, 'targetName': __target, 'memberCall': __member})",
  "__calls.sort(key=lambda __call: (__call['line'], __call['name']))",
  "__json.dumps({'calls': __calls, 'definitions': sorted(__defined)})",
].join("\n");
